################################################################################
### Copy (dynamic) wallpapers

- block:
    - name: "configs : Install Wallpapers - Step 1/6 (set background list)"
      set_fact:
        backgrounds:
          - chroma_blue
          - f36
          - f39
          - zelda
    - name: "configs : Install wallpapers - Step 2/6 (copy wallpapers to build directory)"
      copy:
        src: "{{ role_path }}/files/wallpapers/{{ item }}/{{ item }}.xml"
        dest: "{{ ansible_env.HOME }}/rpmbuild/SOURCES/gnome-background-properties/"
      with_items: "{{ backgrounds }}"
    - name: "configs : Install wallpapers - Step 3/6 (create specs directory)"
      file:
        path: "{{ ansible_env.HOME }}/rpmbuild/SPECS/"
        state: directory
    - name: "configs : Install wallpapers - Step 4/6 (prepare rpm package)"
      copy:
        src: "{{ role_path }}/files/rpmfiles/nikos-wallpapers-gnome.spec"
        dest: "{{ ansible_env.HOME }}/rpmbuild/SPECS/nikos-wallpapers-gnome.spec"
    - name: "configs : Install wallpapers - Step 5/6 (create rpm package)"
      command: "rpmbuild -ba {{ ansible_env.HOME }}/rpmbuild/SPECS/nikos-wallpapers-gnome.spec"
    - name: "configs : Install wallpapers - Step 6/6 (install rpm package)"
      become: true
      community.general.rpm_ostree_pkg:
        name: "{{ ansible_env.HOME }}/rpmbuild/RPMS/noarch/nikos-wallpapers-gnome-1.0-1.noarch.rpm"
        state: present

################################################################################
### Install GNOME Extensions

# FIXME
# - name: "configs : Install GNOME Extensions"
#   become: true
#   petermosmans.customize-gnome.gnome_extensions:
#     - id: "{{ item }}"
#       enable: yes
#   with_items:
#     - 7 # Removable Drive Menu
#     - 307 # Dash to Dock
#     - 615 # AppIndicator and KStatusNotifierItem Support
#     - 744 # Hide Activities Button
#     - 1319 # GSConnect
#     - 2236 # Night Theme Switcher
#     - 3193 # Blur my Shell
#     - 3733 # Tiling Assistant
#     - 3780 # ddterm
#     - 4451 # Logo Menu
#     - 4977 # Sur Clock
#     - 5278 # Pano - Clipboard Manager

################################################################################
### dconf settings

################################################################################
### Change Window Button layout

- name: "configs : dconf : Change Window Button layout"
  dconf:
    key: "/org/gnome/desktop/wm/preferences/button-layout"
    value: "'appmenu:minimize,maximize,close'"

################################################################################
### Modify Clock & Calendar

- block:
    - name: "configs : dconf : Change clock & calendar settings - Step 1/4"
      dconf:
        key: "/org/gnome/desktop/interface/clock-show-seconds"
        value: true
    - name: "configs : dconf : Change clock & calendar settings - Step 2/4"
      dconf:
        key: "/org/gnome/desktop/interface/clock-show-weekday"
        value: true
    - name: "configs : dconf : Change clock & calendar settings - Step 3/4"
      dconf:
        key: "/org/gnome/desktop/datetime/automatic-timezone"
        value: true
    - name: "configs : dconf : Change clock & calendar settings - Step 4/4"
      dconf:
        key: "/org/gnome/desktop/calendar/show-weekdate"
        value: true

################################################################################
### Disable hot-corners

- name: "configs : dconf : Disable hot-corners"
  dconf:
    key: "/org/gnome/desktop/interface/enable-hot-corners"
    value: false

################################################################################
### Disable attach modal dialogs

- name: "configs : dconf : Disable attach modal dialogs"
  dconf:
    key: "/org/gnome/mutter/attach-modal-dialogs"
    value: false

################################################################################
### Enable tap-to-click

- name: "configs : dconf : Enable tap-to-click"
  dconf:
    key: "/org/gnome/desktop/peripherals/touchpad/tap-to-click"
    value: true

################################################################################
### Configure Mouse Acceleration

- name: "configs : dconf : Disable Mouse Acceleration"
  dconf:
    key: "/org/gnome/desktop/peripherals/mouse/accel-profile"
    value: "'flat'"

################################################################################
### Set Fonts

- block:
    - name: "configs : dconf : Set system fonts - Step 1/4"
      dconf:
        key: "/org/gnome/desktop/interface/document-font-name"
        value: "'Space Grotesk 11'"
    - name: "configs : dconf : Set system fonts - Step 2/4"
      dconf:
        key: "/org/gnome/desktop/interface/font-name"
        value: "'Space Grotesk 11'"
    - name: "configs : dconf : Set system fonts - Step 3/4"
      dconf:
        key: "/org/gnome/desktop/interface/monospace-font-name"
        value: "'SpaceMono Nerd Font 11'"
    - name: "configs : dconf : Set system fonts - Step 4/4"
      dconf:
        key: "/org/gnome/desktop/wm/preferences/titlebar-font"
        value: "'Space Grotesk Bold 11'"

################################################################################
### Set GTK# Theme

- name: "configs : dconf : Set GTK+ Theme"
  dconf:
    key: "/org/gnome/desktop/interface/gtk-theme"
    value: "'adw-gtk3-dark'"

################################################################################
### Configure Nautilus

- block:
    - name: "configs : dconf : Configure Nautilus - Step 1/3"
      dconf:
        key: "/org/gnome/nautilus/preferences/default-folder-viewer"
        value: "'list-view'"
    - name: "configs : dconf : Configure Nautilus - Step 2/3"
      dconf:
        key: "/org/gnome/nautilus/list-view/use-tree-view"
        value: true
    - name: "configs : dconf : Configure Nautilus - Step 3/3"
      dconf:
        key: "/org/gtk/gtk4/settings/file-chooser/sort-directories-first"
        value: true

################################################################################
### Configure Keyboard Shortcuts

- block:
    - name: "configs : dconf : Keybindings - Step 1/10"
      dconf:
        key: "/org/gnome/shell/keybindings/toggle-application-view"
        value: "['']"
    - name: "configs : dconf : Keybindings - Step 2/10"
      dconf:
        key: "/org/gnome/shell/keybindings/toggle-message-tray"
        value: "['<Super>a']"
    - name: "configs : dconf : Keybindings - Step 3/10"
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/control-center"
        value: "['<Super>i']"
    - name: "configs : dconf : Keybindings - Step 4/10"
      dconf:
        key: "/org/gnome/settings-daemon/plugins/media-keys/home"
        value: "['<Super>e']"
    - name: "configs : dconf : Keybindings - Step 5/10"
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/activate-window-menu"
        value: "['']"
    - name: "configs : dconf : Keybindings - Step 6/10"
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-input-source"
        value: "['']"
    - name: "configs : dconf : Keybindings - Step 7/10"
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-input-source-backward"
        value: "['']"
    - name: "configs : dconf : Keybindings - Step 8/10"
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/show-desktop"
        value: "['<Super>d']"
    - name: "configs : dconf : Keybindings - Step 9/10"
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-applications"
        value: " ['<Super>Tab']"
    - name: "configs : dconf : Keybindings - Step 10/10"
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-windows"
        value: "['<Alt>Tab']"

################################################################################
### Configure Trash & Tempfile Deletion

- block:
    - name: "configs : dconf : Trash & Tempfile Deletion - Step 1/2"
      dconf:
        key: "/org/gnome/desktop/privacy/remove-old-trash-files"
        value: true
    - name: "configs : dconf : Trash & Tempfile Deletion - Step 2/2"
      dconf:
        key: "/org/gnome/desktop/privacy/remove-old-temp-files"
        value: true
