################################################################################
### Run installation tasks

- include_tasks: rpm-ostree.yml
- include_tasks: flatpaks.yml
- include_tasks: configs.yml
