################################################################################
### Prerequisites

- name: "flatpaks : Add the flathub remote"
  flatpak_remote:
    name: flathub
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
    state: present

################################################################################
### Install packages

- name: "flatpaks : Install flatpaks"
  flatpak:
    name: "{{ item }}"
    state: present
    remote: flathub
  with_items:
    - org.audacityteam.Audacity # Audacity
    - com.bitwarden.desktop # Bitwarden
    - org.blender.Blender # Blender
    - com.cassidyjames.butler # Butler (Home Assistant)
    - org.chromium.Chromium # Chromium
    - com.discordapp.Discord # Discord
    - com.github.wwmm.easyeffects # Easy Effects
    - com.github.tchx84.Flatseal # Flatseal
    - org.gimp.GIMP # GIMP
    - com.dec05eba.gpu_screen_recorder # GPU Screen Recorder
    - fr.handbrake.ghb # Handbrake
    - fr.handbrake.ghb.Plugin.IntelMediaSDK # Handbrake Plugin (Intel QSV)
    - org.inkscape.Inkscape # Inkscape
    - com.makemkv.MakeMKV # MakeMKV
    - com.mattermost.Desktop # Mattermost
    - com.obsproject.Studio # OBS
    - com.obsproject.Studio.Plugin.Gstreamer # OBS Plugin
    - com.obsproject.Studio.Plugin.GStreamerVaapi # OBS Plugin
    - md.obsidian.Obsidian # Obsidian (Markdown Notes)
    - org.onlyoffice.desktopeditors # OnlyOffice
    - tv.plex.PlexDesktop # Plex
    - org.signal.Signal # Signal
    - com.todoist.Todoist # Todoist
    - org.videolan.VLC # VLC
    - org.videolan.VLC.Plugin.bdj # VLC (Blu-Ray Java Menus)
    - org.videolan.VLC.Plugin.makemkv # VLC (MakeMKV decryption)
    - dev.zed.Zed # Zed Editor
